### ISSUE TITLE
Gulp support

### ISSUE THREAD

**Issue by softBarbarian** [feedhenry-templates/quickstart-ionic-app#5]
Hello, I was wondering if there where plans to support Gulp for local development? Ionic team switched to Gulp instead of Grunt a while ago.

Thanks a lot for your help.

**Comment by softBarbarian** [comment]
Hello, any update on this?

**Comment by gentlefox** [comment]
Beta version of Ionic still in FH.
2 versions of jQuery.
Large chunks of code and work-arounds to cater to IE8 and IE9... for mobile phone development?!
4 types of logging methods.
3 types of Angular.

Local development use the conventional Ionic CLI rapid development.
In Gulp, add your modifiers to copy the output files into your feedhenry project on a build, and create the config.json for Cordova plugins to cater for the slobbering unique mess FH does with them!
Thus only use FeedHenry as a staging point for ready builds, add & push, then get FH to process.
